"""
Parse the comprehension question banks in questions_raw/Transcr*.txt and
emit docs/questions.js as a per-transcript map the website renders.

Input file format (per file, one .txt per transcript):

    L1
    What charges are included in Davis' pardon application?
    A) Assault, risk of injury to a minor, and failure to register
    ✅B) Assault, risk of injury to a minor, and probation violation
    C) Strangulation, risk of injury to a minor, and probation violation
    D) Assault, child endangerment, and probation violation

    L1
    How long has Davis been off probation at the time of the hearing?
    ...

- One question per block. Blocks are separated by blank line(s).
- First line of a block: level (L1/L2/L3/L4 or any short non-option label).
- Second line: question prompt.
- Remaining lines: four options starting with `A) `, `B) `, ... `D) `.
- Mark the correct option by prefixing the line with `✅` (whitespace allowed).
- Header blocks like "Level / Question / Anticipated Answer" are skipped.

Output: docs/questions.js exports
    const QUESTIONS_BY_TRANSCRIPT = { TranscrA: [...], TranscrB: [...], ... };
    const QUESTIONS = QUESTIONS_BY_TRANSCRIPT.TranscrA || [];

Usage:
    python scripts/build_questions.py
"""

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "questions_raw"
OUT_FILE = REPO_ROOT / "docs" / "questions.js"

OPTION_RE = re.compile(r"^\s*(?P<check>✅)?\s*(?P<letter>[A-D])\)\s*(?P<text>.*?)\s*$")


HEADER_LINES = {"level", "question", "anticipated answer"}


def parse_file(path: Path, transcript_key: str):
    """Walk lines top-to-bottom: skip blanks/headers, then for each question
    read level → question → 4 option lines (A/B/C/D, optionally ✅-marked)."""
    raw_lines = [l.rstrip() for l in path.read_text(encoding="utf-8").splitlines()]
    n = len(raw_lines)
    i = 0
    questions = []

    def is_blank(s): return not s.strip()
    def is_header(s): return s.strip().lower() in HEADER_LINES

    while i < n:
        if is_blank(raw_lines[i]) or is_header(raw_lines[i]):
            i += 1
            continue

        # Level line
        level = raw_lines[i].strip()
        i += 1

        # Question prompt: next non-blank line
        while i < n and is_blank(raw_lines[i]):
            i += 1
        if i >= n:
            break
        question_text = raw_lines[i].strip()
        i += 1

        # Collect up to 4 option lines
        options = []
        correct_letter = None
        while i < n and len(options) < 4:
            line = raw_lines[i]
            if is_blank(line):
                i += 1
                continue
            m = OPTION_RE.match(line)
            if not m:
                break  # unexpected non-option line — stop collecting for this question
            if m.group("check"):
                correct_letter = m.group("letter")
            options.append(m.group("text"))
            i += 1

        if len(options) == 4:
            correct_index = "ABCD".index(correct_letter) if correct_letter else None
            questions.append({
                "id": f"{transcript_key}_q{len(questions) + 1}",
                "level": level,
                "type": "multiple_choice",
                "text": question_text,
                "options": options,
                "correct_index": correct_index,
                "correct_letter": correct_letter,
            })
        # else: malformed block, skip silently

    return questions


def transcript_key_for(stem: str) -> str:
    # e.g. "TranscrA_Davis" -> "TranscrA"
    return stem.split("_", 1)[0]


def main() -> int:
    if not RAW_DIR.is_dir():
        print(f"ERROR: {RAW_DIR} does not exist.")
        return 1

    by_transcript = {}
    files = sorted(RAW_DIR.glob("Transcr*.txt"))
    if not files:
        print(f"No question files found in {RAW_DIR}.")
        return 1

    for p in files:
        key = transcript_key_for(p.stem)
        questions = parse_file(p, key)
        unmarked = [q for q in questions if q["correct_letter"] is None]
        print(f"  {p.name}: {len(questions)} questions ({len(unmarked)} without ✅)")
        if unmarked:
            for q in unmarked:
                print(f"    [no answer marked] {q['id']}: {q['text'][:80]}")
        by_transcript[key] = questions

    js = []
    js.append("// Generated by scripts/build_questions.py — do not edit directly.")
    js.append("// Edit questions in questions_raw/Transcr*.txt and re-run the script.")
    js.append("")
    js.append("const QUESTIONS_BY_TRANSCRIPT = " + json.dumps(by_transcript, indent=2, ensure_ascii=False) + ";")
    js.append("")
    js.append("// Backwards-compatible default export — first transcript's question set.")
    js.append("const QUESTIONS = QUESTIONS_BY_TRANSCRIPT.TranscrA || [];")
    js.append("")

    OUT_FILE.write_text("\n".join(js), encoding="utf-8")
    print(f"Wrote {OUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
